site_name: Discord MusicBot
site_url: https://musicbot.sudhan.tech
site_author: SudhanPlayz
site_description: >-
  An advanced discord music bot, supports Spotify, Soundcloud, YouTube with Shuffling, Volume Control
  and Web Dashboard with Slash Commands support!

repo_name: sudhanplayz/discord-musicbot
repo_url: https://github.com/sudhanplayz/discord-musicbot
edit_uri: https://github.com/sudhanplayz/discord-musicbot/blob/docs/documentation

theme:
  name: "material"
  logo: "https://raw.githubusercontent.com/SudhanPlayz/Discord-MusicBot/master/assets/logo.gif"
  include_search_page: false
  search_index_only: true
  favicon: "https://raw.githubusercontent.com/SudhanPlayz/Discord-MusicBot/master/assets/logo.gif"
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest

  palette:
    scheme: slate
    primary: "deep purple"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Fira Mono"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - pymdownx.betterem:
      smart_enable: all

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/CodingWithSudhan
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sbySMS7m3v
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/SudhanPlayz"
  generator: false

copyright: Copyright &copy; 2020 - 2021 Sudhan
